//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayIn.Common {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PromotionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PromotionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayIn.Common.PromotionResources", typeof(PromotionResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already participated in this promotion.
        /// </summary>
        public static string CodeAlreadyUsed {
            get {
                return ResourceManager.GetString("CodeAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código introducido no es válido o ya se ha utilizado.
        /// </summary>
        public static string CodeException {
            get {
                return ResourceManager.GetString("CodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This promotion can not be applied to this title.
        /// </summary>
        public static string CodeNotApplicableException {
            get {
                return ResourceManager.GetString("CodeNotApplicableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puedes crear más de 1.000.000 de códigos.
        /// </summary>
        public static string MaxCodeQuantityException {
            get {
                return ResourceManager.GetString("MaxCodeQuantityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only send one code at a time.
        /// </summary>
        public static string SendCodeError {
            get {
                return ResourceManager.GetString("SendCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have the promotion that sent you {0}.
        /// </summary>
        public static string SendCodeMessage {
            get {
                return ResourceManager.GetString("SendCodeMessage", resourceCulture);
            }
        }
    }
}
