// <auto-generated />
namespace PayIn.Infrastructure.Bus.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LinkNodeToRoute : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LinkNodeToRoute));
        
        string IMigrationMetadata.Id
        {
            get { return "201903221154399_LinkNodeToRoute"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
