// <auto-generated />
namespace PayIn.Infrastructure.Bus.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddGeofenceRadiousToStop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGeofenceRadiousToStop));
        
        string IMigrationMetadata.Id
        {
            get { return "201904021613538_AddGeofenceRadiousToStop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
