// <auto-generated />
namespace PayIn.Infrastructure.Public.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v2_3_0_AddDecimalCharToTicketTemplate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2_3_0_AddDecimalCharToTicketTemplate));
        
        string IMigrationMetadata.Id
        {
            get { return "201511271449122_v2_3_0_AddDecimalCharToTicketTemplate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
