// <auto-generated />
namespace PayIn.Infrastructure.Public.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class NewControlPlanning_ControlItem_ServiceTag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewControlPlanning_ControlItem_ServiceTag));
        
        string IMigrationMetadata.Id
        {
            get { return "201501151859531_NewControlPlanning_ControlItem_ServiceTag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
