// <auto-generated />
namespace PayIn.Infrastructure.Public.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v_3_3_0_DeleteVBLBFromGreyList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v_3_3_0_DeleteVBLBFromGreyList));
        
        string IMigrationMetadata.Id
        {
            get { return "201603110918120_v_3_3_0_DeleteVBLBFromGreyList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
