// <auto-generated />
namespace PayIn.Infrastructure.Public.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingnewAttributestoEventEntranceTypeandEntrance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingnewAttributestoEventEntranceTypeandEntrance));
        
        string IMigrationMetadata.Id
        {
            get { return "201706160747352_Adding new Attributes to Event EntranceType and Entrance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
