// <auto-generated />
namespace PayIn.Infrastructure.Public.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TicketWithExternalLogin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TicketWithExternalLogin));
        
        string IMigrationMetadata.Id
        {
            get { return "201801181230582_TicketWithExternalLogin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
