// <auto-generated />
namespace PayIn.Infrastructure.Internal.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v2_1_0_UserStatePinRetries : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2_1_0_UserStatePinRetries));
        
        string IMigrationMetadata.Id
        {
            get { return "201509161614035_v2_1_0_UserStatePinRetries"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
