// <auto-generated />
namespace PayIn.Infrastructure.Internal.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class paymentConcessionLoginInitialize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(paymentConcessionLoginInitialize));
        
        string IMigrationMetadata.Id
        {
            get { return "201708051536214_paymentConcessionLoginInitialize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
