// <auto-generated />
namespace PayIn.Infrastructure.SmartCity.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddPowerPriceToContract : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPowerPriceToContract));
        
        string IMigrationMetadata.Id
        {
            get { return "201903142352087_AddPowerPriceToContract"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
