//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayIn.Infrastructure.Sabadell {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SabadellTransactions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SabadellTransactions() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayIn.Infrastructure.Sabadell.SabadellTransactions", typeof(SabadellTransactions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transacción aprobada.
        /// </summary>
        public static string Response_0 {
            get {
                return ResourceManager.GetString("Response_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transacción aprobada previa identificación del titular.
        /// </summary>
        public static string Response_1 {
            get {
                return ResourceManager.GetString("Response_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta caducada.
        /// </summary>
        public static string Response_101 {
            get {
                return ResourceManager.GetString("Response_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta bloqueada transitoriamente o bajo sospecha de fraude.
        /// </summary>
        public static string Response_102 {
            get {
                return ResourceManager.GetString("Response_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación no permitida.
        /// </summary>
        public static string Response_104 {
            get {
                return ResourceManager.GetString("Response_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de intentos excedido.
        /// </summary>
        public static string Response_106 {
            get {
                return ResourceManager.GetString("Response_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contactar con el emisor.
        /// </summary>
        public static string Response_107 {
            get {
                return ResourceManager.GetString("Response_107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identificación invalida del comercio o terminal.
        /// </summary>
        public static string Response_109 {
            get {
                return ResourceManager.GetString("Response_109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe inválido.
        /// </summary>
        public static string Response_110 {
            get {
                return ResourceManager.GetString("Response_110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta no soporta el tipo de operación solicitado.
        /// </summary>
        public static string Response_114 {
            get {
                return ResourceManager.GetString("Response_114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disponible insuficiente.
        /// </summary>
        public static string Response_116 {
            get {
                return ResourceManager.GetString("Response_116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta no registrada.
        /// </summary>
        public static string Response_118 {
            get {
                return ResourceManager.GetString("Response_118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transacción denegada.
        /// </summary>
        public static string Response_119 {
            get {
                return ResourceManager.GetString("Response_119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta no efectiva.
        /// </summary>
        public static string Response_125 {
            get {
                return ResourceManager.GetString("Response_125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error CVV2/CVC2.
        /// </summary>
        public static string Response_129 {
            get {
                return ResourceManager.GetString("Response_129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contactar con el emisor: sospecha de fraude.
        /// </summary>
        public static string Response_167 {
            get {
                return ResourceManager.GetString("Response_167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta ajena al servicio.
        /// </summary>
        public static string Response_180 {
            get {
                return ResourceManager.GetString("Response_180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta con restricciones de débito o crédito.
        /// </summary>
        public static string Response_181 {
            get {
                return ResourceManager.GetString("Response_181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta con restricciones de débito o crédito.
        /// </summary>
        public static string Response_182 {
            get {
                return ResourceManager.GetString("Response_182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de autenticación.
        /// </summary>
        public static string Response_184 {
            get {
                return ResourceManager.GetString("Response_184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Denegación sin especificar el motivo.
        /// </summary>
        public static string Response_190 {
            get {
                return ResourceManager.GetString("Response_190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de caducidad erronea.
        /// </summary>
        public static string Response_191 {
            get {
                return ResourceManager.GetString("Response_191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transacción aprobada.
        /// </summary>
        public static string Response_2 {
            get {
                return ResourceManager.GetString("Response_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta cadudaca.
        /// </summary>
        public static string Response_201 {
            get {
                return ResourceManager.GetString("Response_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta bloqueada transitoriamente o bajo sospecha de fraude.
        /// </summary>
        public static string Response_202 {
            get {
                return ResourceManager.GetString("Response_202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación no permitida.
        /// </summary>
        public static string Response_204 {
            get {
                return ResourceManager.GetString("Response_204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contactar con el emisor.
        /// </summary>
        public static string Response_207 {
            get {
                return ResourceManager.GetString("Response_207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta perdida o robada.
        /// </summary>
        public static string Response_208 {
            get {
                return ResourceManager.GetString("Response_208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta perdida o robada.
        /// </summary>
        public static string Response_209 {
            get {
                return ResourceManager.GetString("Response_209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error CVV2/CVC2.
        /// </summary>
        public static string Response_280 {
            get {
                return ResourceManager.GetString("Response_280", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Denegación sin especificar el motivo.
        /// </summary>
        public static string Response_290 {
            get {
                return ResourceManager.GetString("Response_290", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anulación aceptada.
        /// </summary>
        public static string Response_400 {
            get {
                return ResourceManager.GetString("Response_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra la operación original o time-out excedido.
        /// </summary>
        public static string Response_480 {
            get {
                return ResourceManager.GetString("Response_480", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anulación aceptada.
        /// </summary>
        public static string Response_481 {
            get {
                return ResourceManager.GetString("Response_481", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conciliación aceptada.
        /// </summary>
        public static string Response_500 {
            get {
                return ResourceManager.GetString("Response_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No encontrada la operación original o time-out excedido.
        /// </summary>
        public static string Response_501 {
            get {
                return ResourceManager.GetString("Response_501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No encontrada la operación original o time-out excedida.
        /// </summary>
        public static string Response_503 {
            get {
                return ResourceManager.GetString("Response_503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comercio no registrado en el FUC.
        /// </summary>
        public static string Response_904 {
            get {
                return ResourceManager.GetString("Response_904", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud tarjeta incorrecta.
        /// </summary>
        public static string Response_9064 {
            get {
                return ResourceManager.GetString("Response_9064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe método de pago.
        /// </summary>
        public static string Response_9078 {
            get {
                return ResourceManager.GetString("Response_9078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de sistema.
        /// </summary>
        public static string Response_909 {
            get {
                return ResourceManager.GetString("Response_909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta no existe.
        /// </summary>
        public static string Response_9093 {
            get {
                return ResourceManager.GetString("Response_9093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Denegación de los emisores.
        /// </summary>
        public static string Response_9094 {
            get {
                return ResourceManager.GetString("Response_9094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación segura no es posible.
        /// </summary>
        public static string Response_9104 {
            get {
                return ResourceManager.GetString("Response_9104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Emisor no disponible.
        /// </summary>
        public static string Response_912 {
            get {
                return ResourceManager.GetString("Response_912", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transmisión duplicada.
        /// </summary>
        public static string Response_913 {
            get {
                return ResourceManager.GetString("Response_913", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo límite de pago superado.
        /// </summary>
        public static string Response_9142 {
            get {
                return ResourceManager.GetString("Response_9142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe demasiado pequeño.
        /// </summary>
        public static string Response_916 {
            get {
                return ResourceManager.GetString("Response_916", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pueden hacer operaciones seguras.
        /// </summary>
        public static string Response_9218 {
            get {
                return ResourceManager.GetString("Response_9218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check-digit erroneo.
        /// </summary>
        public static string Response_9253 {
            get {
                return ResourceManager.GetString("Response_9253", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preautorizaciones no habilitadas.
        /// </summary>
        public static string Response_9256 {
            get {
                return ResourceManager.GetString("Response_9256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Límite operativo excedido.
        /// </summary>
        public static string Response_9261 {
            get {
                return ResourceManager.GetString("Response_9261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time-out excedido.
        /// </summary>
        public static string Response_928 {
            get {
                return ResourceManager.GetString("Response_928", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supera alertas bloqueantes.
        /// </summary>
        public static string Response_9281 {
            get {
                return ResourceManager.GetString("Response_9281", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supera alertas bloqueantes.
        /// </summary>
        public static string Response_9283 {
            get {
                return ResourceManager.GetString("Response_9283", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transacción anulada anteriormente.
        /// </summary>
        public static string Response_940 {
            get {
                return ResourceManager.GetString("Response_940", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transacción de autorización ya anulada por una anulación anterior.
        /// </summary>
        public static string Response_941 {
            get {
                return ResourceManager.GetString("Response_941", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transacción original denegada.
        /// </summary>
        public static string Response_942 {
            get {
                return ResourceManager.GetString("Response_942", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de la transacción original distintos.
        /// </summary>
        public static string Response_943 {
            get {
                return ResourceManager.GetString("Response_943", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sesión erronea.
        /// </summary>
        public static string Response_944 {
            get {
                return ResourceManager.GetString("Response_944", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transimisión duplicada.
        /// </summary>
        public static string Response_945 {
            get {
                return ResourceManager.GetString("Response_945", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación a anular en proceso.
        /// </summary>
        public static string Response_946 {
            get {
                return ResourceManager.GetString("Response_946", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transmisión duplicada en proceso.
        /// </summary>
        public static string Response_947 {
            get {
                return ResourceManager.GetString("Response_947", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terminal inoperativo.
        /// </summary>
        public static string Response_949 {
            get {
                return ResourceManager.GetString("Response_949", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Devolución no permitida.
        /// </summary>
        public static string Response_950 {
            get {
                return ResourceManager.GetString("Response_950", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Violación normativa.
        /// </summary>
        public static string Response_965 {
            get {
                return ResourceManager.GetString("Response_965", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transacción aprobada.
        /// </summary>
        public static string Response_99 {
            get {
                return ResourceManager.GetString("Response_99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Emisor no disponible.
        /// </summary>
        public static string Response_9912 {
            get {
                return ResourceManager.GetString("Response_9912", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la confirmación.
        /// </summary>
        public static string Response_9913 {
            get {
                return ResourceManager.GetString("Response_9913", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación &quot;KO&quot;.
        /// </summary>
        public static string Response_9914 {
            get {
                return ResourceManager.GetString("Response_9914", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pago cancelado.
        /// </summary>
        public static string Response_9915 {
            get {
                return ResourceManager.GetString("Response_9915", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anulación de preautorización realizada por el sistema.
        /// </summary>
        public static string Response_9928 {
            get {
                return ResourceManager.GetString("Response_9928", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anulación de preautorización realizada por el comercio.
        /// </summary>
        public static string Response_9929 {
            get {
                return ResourceManager.GetString("Response_9929", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transacción simultánea.
        /// </summary>
        public static string Response_9997 {
            get {
                return ResourceManager.GetString("Response_9997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado operación: Solicitada.
        /// </summary>
        public static string Response_9998 {
            get {
                return ResourceManager.GetString("Response_9998", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado operación: Autenticando.
        /// </summary>
        public static string Response_9999 {
            get {
                return ResourceManager.GetString("Response_9999", resourceCulture);
            }
        }
    }
}
