//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayIn.Infrastructure.Sabadell {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SabadellErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SabadellErrors() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayIn.Infrastructure.Sabadell.SabadellErrors", typeof(SabadellErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El sistema está ocupado, inténtelo más tarde.
        /// </summary>
        public static string MSG0000 {
            get {
                return ResourceManager.GetString("MSG0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de pedido repetido.
        /// </summary>
        public static string MSG0001 {
            get {
                return ResourceManager.GetString("MSG0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Bin de la tarjeta no está dado de alta en FINANET.
        /// </summary>
        public static string MSG0002 {
            get {
                return ResourceManager.GetString("MSG0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El sistema está arrancando, inténtelo en unos momentos.
        /// </summary>
        public static string MSG0003 {
            get {
                return ResourceManager.GetString("MSG0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de auntenticación.
        /// </summary>
        public static string MSG0004 {
            get {
                return ResourceManager.GetString("MSG0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe método de pago válido para su tarjeta.
        /// </summary>
        public static string MSG0005 {
            get {
                return ResourceManager.GetString("MSG0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta ajena al servicio.
        /// </summary>
        public static string MSG0006 {
            get {
                return ResourceManager.GetString("MSG0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Faltan datos, por favor compruebe que su navegador acepta cookies.
        /// </summary>
        public static string MSG0007 {
            get {
                return ResourceManager.GetString("MSG0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en datos enviado. Contacte con su comercio.
        /// </summary>
        public static string MSG0008 {
            get {
                return ResourceManager.GetString("MSG0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta el campo  Ds_Merchant_Terminal.
        /// </summary>
        public static string SIS0010 {
            get {
                return ResourceManager.GetString("SIS0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de formato en Ds_Merchant_Terminal.
        /// </summary>
        public static string SIS0011 {
            get {
                return ResourceManager.GetString("SIS0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de formato en Ds_Merchant_Order.
        /// </summary>
        public static string SIS0014 {
            get {
                return ResourceManager.GetString("SIS0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta el campo Ds_Merchant_Currency.
        /// </summary>
        public static string SIS0015 {
            get {
                return ResourceManager.GetString("SIS0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de formato en Ds_Merchant_Currency.
        /// </summary>
        public static string SIS0016 {
            get {
                return ResourceManager.GetString("SIS0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta el campo Ds_Merchant_Amount.
        /// </summary>
        public static string SIS0018 {
            get {
                return ResourceManager.GetString("SIS0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de formato en Ds_Merchant_Amount.
        /// </summary>
        public static string SIS0019 {
            get {
                return ResourceManager.GetString("SIS0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta el campo Ds_Merchant_Signature.
        /// </summary>
        public static string SIS0020 {
            get {
                return ResourceManager.GetString("SIS0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ds_Merchant_Signature no tiene datos.
        /// </summary>
        public static string SIS0021 {
            get {
                return ResourceManager.GetString("SIS0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de formato en Ds_TransactionType.
        /// </summary>
        public static string SIS0022 {
            get {
                return ResourceManager.GetString("SIS0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ds_TransactionType tiene un valor desconocido.
        /// </summary>
        public static string SIS0023 {
            get {
                return ResourceManager.GetString("SIS0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ds_ConsumerLanguage excede de 3 posiciones.
        /// </summary>
        public static string SIS0024 {
            get {
                return ResourceManager.GetString("SIS0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de formato en Ds_ConsumerLanguage.
        /// </summary>
        public static string SIS0025 {
            get {
                return ResourceManager.GetString("SIS0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe el comercio.
        /// </summary>
        public static string SIS0026 {
            get {
                return ResourceManager.GetString("SIS0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La moneda no coincide con la del terminal.
        /// </summary>
        public static string SIS0027 {
            get {
                return ResourceManager.GetString("SIS0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El terminal está dado de baja.
        /// </summary>
        public static string SIS0028 {
            get {
                return ResourceManager.GetString("SIS0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En un pago con tarjeta h llegado un tipo que no es pago.
        /// </summary>
        public static string SIS0030 {
            get {
                return ResourceManager.GetString("SIS0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Método de pago no definido.
        /// </summary>
        public static string SIS0031 {
            get {
                return ResourceManager.GetString("SIS0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en acceso a la BBDD.
        /// </summary>
        public static string SIS0034 {
            get {
                return ResourceManager.GetString("SIS0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en JAVA.
        /// </summary>
        public static string SIS0038 {
            get {
                return ResourceManager.GetString("SIS0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El comercio no  tiene ningún método de pago.
        /// </summary>
        public static string SIS0040 {
            get {
                return ResourceManager.GetString("SIS0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el cálculo del algoritmo HASH.
        /// </summary>
        public static string SIS0041 {
            get {
                return ResourceManager.GetString("SIS0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el cálculo del algoritmo HASH.
        /// </summary>
        public static string SIS0042 {
            get {
                return ResourceManager.GetString("SIS0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al realizar la notificación on-line.
        /// </summary>
        public static string SIS0043 {
            get {
                return ResourceManager.GetString("SIS0043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Bin de la tarjeta no está dado de alta.
        /// </summary>
        public static string SIS0046 {
            get {
                return ResourceManager.GetString("SIS0046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de pedido repetido.
        /// </summary>
        public static string SIS0051 {
            get {
                return ResourceManager.GetString("SIS0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe operación sobre la que realizar la devolución.
        /// </summary>
        public static string SIS0054 {
            get {
                return ResourceManager.GetString("SIS0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La operación sobre la que se desea realizar la devolución no es una operación válida.
        /// </summary>
        public static string SIS0055 {
            get {
                return ResourceManager.GetString("SIS0055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La operación sobre la que se desea realizar la devolución no está autorizada.
        /// </summary>
        public static string SIS0056 {
            get {
                return ResourceManager.GetString("SIS0056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El importe a devolver supera el permitido.
        /// </summary>
        public static string SIS0057 {
            get {
                return ResourceManager.GetString("SIS0057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inconsistencia de datos.
        /// </summary>
        public static string SIS0058 {
            get {
                return ResourceManager.GetString("SIS0058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe la operación sobre la que realizar la confirmación.
        /// </summary>
        public static string SIS0059 {
            get {
                return ResourceManager.GetString("SIS0059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe confirmación asociada a la preautorización.
        /// </summary>
        public static string SIS0060 {
            get {
                return ResourceManager.GetString("SIS0060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La preautorización sobre la que se desea confirmar no está autorizada.
        /// </summary>
        public static string SIS0061 {
            get {
                return ResourceManager.GetString("SIS0061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El importe a confirmar supera el permitido.
        /// </summary>
        public static string SIS0062 {
            get {
                return ResourceManager.GetString("SIS0062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el número de tarjeta.
        /// </summary>
        public static string SIS0063 {
            get {
                return ResourceManager.GetString("SIS0063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el número de tarjeta.
        /// </summary>
        public static string SIS0064 {
            get {
                return ResourceManager.GetString("SIS0064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el número de tarjeta.
        /// </summary>
        public static string SIS0065 {
            get {
                return ResourceManager.GetString("SIS0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la caducidad de la tarjeta.
        /// </summary>
        public static string SIS0066 {
            get {
                return ResourceManager.GetString("SIS0066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error e nla caducidad de la tarjeta.
        /// </summary>
        public static string SIS0067 {
            get {
                return ResourceManager.GetString("SIS0067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la caducidad de la tarjeta.
        /// </summary>
        public static string SIS0068 {
            get {
                return ResourceManager.GetString("SIS0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la caducidad de la tarjeta.
        /// </summary>
        public static string SIS0069 {
            get {
                return ResourceManager.GetString("SIS0069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al desmontar XML de entrada.
        /// </summary>
        public static string SIS007 {
            get {
                return ResourceManager.GetString("SIS007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la caducidad de la tarjeta.
        /// </summary>
        public static string SIS0070 {
            get {
                return ResourceManager.GetString("SIS0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta caducada.
        /// </summary>
        public static string SIS0071 {
            get {
                return ResourceManager.GetString("SIS0071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación no anulable.
        /// </summary>
        public static string SIS0072 {
            get {
                return ResourceManager.GetString("SIS0072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta el campo.
        /// </summary>
        public static string SIS0074 {
            get {
                return ResourceManager.GetString("SIS0074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor tiene menos de 4 posiciones o más de 12.
        /// </summary>
        public static string SIS0075 {
            get {
                return ResourceManager.GetString("SIS0075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor no es numérico.
        /// </summary>
        public static string SIS0076 {
            get {
                return ResourceManager.GetString("SIS0076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor desconocido.
        /// </summary>
        public static string SIS0078 {
            get {
                return ResourceManager.GetString("SIS0078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al realizar el pago con tarjeta.
        /// </summary>
        public static string SIS0079 {
            get {
                return ResourceManager.GetString("SIS0079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta el campo Ds_Merchant_MerchantCode.
        /// </summary>
        public static string SIS008 {
            get {
                return ResourceManager.GetString("SIS008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se han perdido los datos almacenados.
        /// </summary>
        public static string SIS0081 {
            get {
                return ResourceManager.GetString("SIS0081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor de Ds_Merchant_ExpiryDate no ocupa 4 posiciones.
        /// </summary>
        public static string SIS0089 {
            get {
                return ResourceManager.GetString("SIS0089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de formato en Ds_Merchant_MerchantCode.
        /// </summary>
        public static string SIS009 {
            get {
                return ResourceManager.GetString("SIS009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor de  Ds_Merchant_ExpiryDate es nulo.
        /// </summary>
        public static string SIS0092 {
            get {
                return ResourceManager.GetString("SIS0092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta no encontrada en tabla de rangos.
        /// </summary>
        public static string SIS0093 {
            get {
                return ResourceManager.GetString("SIS0093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La tarjeta no fue autenticada como 3D secure.
        /// </summary>
        public static string SIS0094 {
            get {
                return ResourceManager.GetString("SIS0094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor no permitido.
        /// </summary>
        public static string SIS0112 {
            get {
                return ResourceManager.GetString("SIS0112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha llamado a un GET en lugar de un POST.
        /// </summary>
        public static string SIS0114 {
            get {
                return ResourceManager.GetString("SIS0114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe operación sobre la que realizar el pago de la cuota.
        /// </summary>
        public static string SIS0115 {
            get {
                return ResourceManager.GetString("SIS0115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La operación sobre la que se desea pagar una cuota no es válida.
        /// </summary>
        public static string SIS0116 {
            get {
                return ResourceManager.GetString("SIS0116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La operación sobre la que se desea pagar una cuota no está autorizada.
        /// </summary>
        public static string SIS0117 {
            get {
                return ResourceManager.GetString("SIS0117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de Confirmación de Autorización no puede superar en más de 7 días a la preautorización.
        /// </summary>
        public static string SIS0132 {
            get {
                return ResourceManager.GetString("SIS0132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de confirmación de Autenticación no puede superar en más de 45 días la autenticación previa.
        /// </summary>
        public static string SIS0133 {
            get {
                return ResourceManager.GetString("SIS0133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El pago recurrente inicial está duplicado.
        /// </summary>
        public static string SIS0139 {
            get {
                return ResourceManager.GetString("SIS0139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo excedido para el pago.
        /// </summary>
        public static string SIS0142 {
            get {
                return ResourceManager.GetString("SIS0142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe supera límite permitido para el comercio.
        /// </summary>
        public static string SIS0198 {
            get {
                return ResourceManager.GetString("SIS0198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de operaciones supera el límite permitido para el comercio.
        /// </summary>
        public static string SIS0199 {
            get {
                return ResourceManager.GetString("SIS0199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El impote acumulado supera el limite permitido para el comercio.
        /// </summary>
        public static string SIS0200 {
            get {
                return ResourceManager.GetString("SIS0200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El comercio no admite devoluciones.
        /// </summary>
        public static string SIS0214 {
            get {
                return ResourceManager.GetString("SIS0214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El CVV2 tiene más de tres posiciones.
        /// </summary>
        public static string SIS0216 {
            get {
                return ResourceManager.GetString("SIS0216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de formato en CVV2.
        /// </summary>
        public static string SIS0217 {
            get {
                return ResourceManager.GetString("SIS0217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La entrada &quot;operaciones&quot; no permite pagos seguros.
        /// </summary>
        public static string SIS0218 {
            get {
                return ResourceManager.GetString("SIS0218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de operaciones de la tarjeta supera el límite permitido para el comercio.
        /// </summary>
        public static string SIS0219 {
            get {
                return ResourceManager.GetString("SIS0219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El importe acumulado de la tarjeta supera el límite permitido para el comercio.
        /// </summary>
        public static string SIS0220 {
            get {
                return ResourceManager.GetString("SIS0220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El CVV2 es obligatorio.
        /// </summary>
        public static string SIS0221 {
            get {
                return ResourceManager.GetString("SIS0221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe anulación asociada a la preautorización.
        /// </summary>
        public static string SIS0222 {
            get {
                return ResourceManager.GetString("SIS0222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La preautorización que se desea anular no está autorizada.
        /// </summary>
        public static string SIS0223 {
            get {
                return ResourceManager.GetString("SIS0223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El comercio no permite anulaciones por no tener firma ampliada.
        /// </summary>
        public static string SIS0224 {
            get {
                return ResourceManager.GetString("SIS0224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe operación.
        /// </summary>
        public static string SIS0225 {
            get {
                return ResourceManager.GetString("SIS0225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inconsistencia de datos en la validación de una anulación.
        /// </summary>
        public static string SIS0226 {
            get {
                return ResourceManager.GetString("SIS0226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor no válido.
        /// </summary>
        public static string SIS0227 {
            get {
                return ResourceManager.GetString("SIS0227", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe el código de pago aplazado solicitado.
        /// </summary>
        public static string SIS0229 {
            get {
                return ResourceManager.GetString("SIS0229", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El comercio no permite el envío de tarjeta.
        /// </summary>
        public static string SIS0252 {
            get {
                return ResourceManager.GetString("SIS0252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La tarjeta no cumple el check-digit.
        /// </summary>
        public static string SIS0253 {
            get {
                return ResourceManager.GetString("SIS0253", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de operaciones por IP supera el máximo permitido para el comercio.
        /// </summary>
        public static string SIS0254 {
            get {
                return ResourceManager.GetString("SIS0254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El importe acumulado por IP supera el límite permitido para el comercio.
        /// </summary>
        public static string SIS0255 {
            get {
                return ResourceManager.GetString("SIS0255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El comercio no puede realizar preautorizaciones.
        /// </summary>
        public static string SIS0256 {
            get {
                return ResourceManager.GetString("SIS0256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La tarjeta no permite preautorizaciones.
        /// </summary>
        public static string SIS0257 {
            get {
                return ResourceManager.GetString("SIS0257", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inconsistencia en datos de confirmación.
        /// </summary>
        public static string SIS0258 {
            get {
                return ResourceManager.GetString("SIS0258", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación supera alguna limitación de operatoria definida por Banco Sabadell.
        /// </summary>
        public static string SIS0261 {
            get {
                return ResourceManager.GetString("SIS0261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de operación no activado para este comercio.
        /// </summary>
        public static string SIS0270 {
            get {
                return ResourceManager.GetString("SIS0270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de operación desconocida o no permitida para esta entrada al TPV virtual.
        /// </summary>
        public static string SIS0274 {
            get {
                return ResourceManager.GetString("SIS0274", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operación supera alguna limitación operatoria definida por Banco Sabadell.
        /// </summary>
        public static string SIS0281 {
            get {
                return ResourceManager.GetString("SIS0281", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al validar  los datos de la operación &quot;Tarjeta en Archivo (P.Suscripciones/P.Exprés)&quot; inicial.
        /// </summary>
        public static string SIS0296 {
            get {
                return ResourceManager.GetString("SIS0296", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Superado el número máximo de operaciones para realizar transacciones sucesivas.
        /// </summary>
        public static string SIS0297 {
            get {
                return ResourceManager.GetString("SIS0297", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El comercio no permite realizar operaciones de Pago con Referencia.
        /// </summary>
        public static string SIS0298 {
            get {
                return ResourceManager.GetString("SIS0298", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El comercio no pertenece al grupo especificado en Ds_Merchant_Group.
        /// </summary>
        public static string SIS0319 {
            get {
                return ResourceManager.GetString("SIS0319", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La referencia indicada en Ds_Merchant_Identifier no está asociada al comercio.
        /// </summary>
        public static string SIS0321 {
            get {
                return ResourceManager.GetString("SIS0321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de formato en Ds_Merchant_Group.
        /// </summary>
        public static string SIS0322 {
            get {
                return ResourceManager.GetString("SIS0322", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha pedido no mostrar pantallas pero no se ha enviada ninguna referencia de tarjeta.
        /// </summary>
        public static string SIS0325 {
            get {
                return ResourceManager.GetString("SIS0325", resourceCulture);
            }
        }
    }
}
