// <auto-generated />
namespace PayIn.Infrastructure.Security.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class UserInformation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserInformation));
        
        string IMigrationMetadata.Id
        {
            get { return "201412151611148_UserInformation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
