// <auto-generated />
namespace PayIn.Infrastructure.Security.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ConfirmEmailUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConfirmEmailUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201505131935433_ConfirmEmailUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
