// <auto-generated />
namespace PayIn.Infrastructure.Security.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v2_1_1_ApplicationUserNullableBirthday : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2_1_1_ApplicationUserNullableBirthday));
        
        string IMigrationMetadata.Id
        {
            get { return "201510271845587_v2_1_1_ApplicationUserNullableBirthday"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
