//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayIn.Common.Security {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SecurityResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecurityResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayIn.Common.Security.SecurityResources", typeof(SecurityResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the terms and conditions of this.
        /// </summary>
        public static string AcceptTerms {
            get {
                return ResourceManager.GetString("AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To register you must accept terms of service.
        /// </summary>
        public static string AcceptTermsException {
            get {
                return ResourceManager.GetString("AcceptTermsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user account is blocked for security reasons. Please, contact our administrator at info@pay-in.es to solve the incidence..
        /// </summary>
        public static string AccountBlockedBefore {
            get {
                return ResourceManager.GetString("AccountBlockedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement.
        /// </summary>
        public static string Agreement {
            get {
                return ResourceManager.GetString("Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday/Foundation date.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept terms.
        /// </summary>
        public static string CheckAcceptTerms {
            get {
                return ResourceManager.GetString("CheckAcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company contact.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and his confirm must be identical..
        /// </summary>
        public static string ComparePassword {
            get {
                return ResourceManager.GetString("ComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma el registro de la empresa en Pay[in].
        /// </summary>
        public static string ConfirmCompanyEmailSubject {
            get {
                return ResourceManager.GetString("ConfirmCompanyEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Estimado/a  {2},&lt;/p&gt;
        ///&lt;p&gt;Gracias por registrarse en la APP Finestrat. Por razones de seguridad, necesitamos validar que este correo electrónico le pertenece. Por esta razón, le hemos enviado este correo electrónico con el enlace que le permitirá terminar el registro:&lt;/p&gt;
        ///&lt;a href=&quot;{4}/Account/ConfirmEmail?userid={0}&amp;code={1}&amp;email={3}&quot;&gt;{4}/Account/ConfirmEmail&lt;/a&gt;                   &lt;br /&gt;
        ///&lt;p&gt;Si ha recibido este correo por error o no se ha registrado en la APP Finestrat, por favor ignore y elimine este c [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ConfirmEmailContent_Finestrat {
            get {
                return ResourceManager.GetString("ConfirmEmailContent_Finestrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Estimado/a  {2},&lt;/p&gt;
        ///&lt;p&gt;Gracias por registrarse en la APP Turisme Vilamarxant. Por razones de seguridad, necesitamos validar que este correo electrónico le pertenece. Por esta razón, le hemos enviado este correo electrónico con el enlace que le permitirá terminar el registro:&lt;/p&gt;
        ///&lt;a href=&quot;{4}/Account/ConfirmEmail?userid={0}&amp;code={1}&amp;email={3}&quot;&gt;{4}/Account/ConfirmEmail&lt;/a&gt;                   &lt;br /&gt;
        ///&lt;p&gt;Si ha recibido este correo por error o no se ha registrado en la APP Turisme Vilamarxant, por favor ign [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ConfirmEmailContent_Vilamarxant {
            get {
                return ResourceManager.GetString("ConfirmEmailContent_Vilamarxant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; {2},&lt;/p&gt;
        ///&lt;p&gt;Gracias por registrar su empresa en Pay[in]. Por razones de seguridad, necesitamos validar que este correo electrónico pertenece a su empresa. Por esta razón, le hemos enviado este correo electrónico con el enlace que le permitirá terminar el registro:&lt;/p&gt;
        ///&lt;a href=&quot;{4}/Account/ConfirmEmail?userid={0}&amp;code={1}&amp;email={3}&quot;&gt;{4}/Account/ConfirmEmail&lt;/a&gt;                   &lt;br /&gt;
        ///&lt;p&gt;Si ha recibido este correo por error o no ha registrado su empresa en Pay[in], por favor ignore y elimine este cor [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ConfirmEmailContentCompany {
            get {
                return ResourceManager.GetString("ConfirmEmailContentCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Estimado/a  {2},&lt;/p&gt;
        ///&lt;p&gt;Gracias por registrarse en Pay[in] como autónomo. Por razones de seguridad, necesitamos validar que este correo electrónico le pertenece. Por esta razón, le hemos enviado este correo electrónico con el enlace que le permitirá terminar el registro:&lt;/p&gt;
        ///&lt;a href=&quot;{4}/Account/ConfirmEmail?userid={0}&amp;code={1}&amp;email={3}&quot;&gt;{4}/Account/ConfirmEmail&lt;/a&gt;                   &lt;br /&gt;
        ///&lt;p&gt;Si ha recibido este correo por error o no se ha registrado en Pay[in], por favor ignore y elimine este corre [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ConfirmEmailContentSelfEmployed {
            get {
                return ResourceManager.GetString("ConfirmEmailContentSelfEmployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Estimado/a {2},&lt;/p&gt;
        ///&lt;p&gt;Gracias por registrate en Pay[in]. Por razones de seguridad, necesitamos validar que este correo electrónico te pertenece. Por esta razón, le hemos enviado este correo electrónico con el enlace que le permitirá terminar el registro:&lt;/p&gt;
        ///&lt;a href=&quot;{4}/Account/ConfirmEmail?userid={0}&amp;code={1}&amp;email={3}&quot;&gt;{4}/Account/ConfirmEmail&lt;/a&gt;                   &lt;br /&gt;
        ///&lt;p&gt;Si ha recibido este correo por error o no se ha registrado en Pay[in], por favir ignore y elimina este correo de su bandeja  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ConfirmEmailContentUser {
            get {
                return ResourceManager.GetString("ConfirmEmailContentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma el registro en Pay[in].
        /// </summary>
        public static string ConfirmEmailSubject {
            get {
                return ResourceManager.GetString("ConfirmEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma el registro en la APP Finestrat.
        /// </summary>
        public static string ConfirmEmailSubject_Finestrat {
            get {
                return ResourceManager.GetString("ConfirmEmailSubject_Finestrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma el registro en la APP Turisme Vilamarxant.
        /// </summary>
        public static string ConfirmEmailSubject_Vilamarxant {
            get {
                return ResourceManager.GetString("ConfirmEmailSubject_Vilamarxant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracias por registrarte en el sistema Pay[in]. Recibirás un email en tu cuenta donde deberás confirmar tu registro. Para ello, haz click en el link recibido en el mail o copia el userID y Code del mail y pegalo en los campos correspondientes del formulario. Por favor, si no recibes el mail intenta registrarte de nuevo. Si todavía no recibes el mail enviamos un mail a system@pay-in.es..
        /// </summary>
        public static string ConfirmEmailText {
            get {
                return ResourceManager.GetString("ConfirmEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracias por registrarte en la APP Finestrat. Recibirás un email en tu cuenta donde deberás confirmar tu registro. Para ello, haz click en el link recibido en el mail o copia el userID y Code del mail y pegalo en los campos correspondientes del formulario. Por favor, si no recibes el mail intenta registrarte de nuevo. Si todavía no recibes el mail enviamos un mail a kikeapp@finestrat.org..
        /// </summary>
        public static string ConfirmEmailText_Finestrat {
            get {
                return ResourceManager.GetString("ConfirmEmailText_Finestrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracias por registrarte en la APP Turisme Vilamarxant. Recibirás un email en tu cuenta donde deberás confirmar tu registro. Para ello, haz click en el link recibido en el mail o copia el userID y Code del mail y pegalo en los campos correspondientes del formulario. Por favor, si no recibes el mail intenta registrarte de nuevo. Si todavía no recibes el mail enviamos un mail a app@vilamarxant.es..
        /// </summary>
        public static string ConfirmEmailText_Vilamarxant {
            get {
                return ResourceManager.GetString("ConfirmEmailText_Vilamarxant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar registro en Pay[in].
        /// </summary>
        public static string ConfirmEmailUrlText {
            get {
                return ResourceManager.GetString("ConfirmEmailUrlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En breve recibirá un correo en su cuenta. Para crear la nueva contraseña, pulsa sobre el link recibido en el correo o copia el &quot;User ID&quot; y el &quot;Code&quot; desde el correo y pégalo en su campo correspondiente..
        /// </summary>
        public static string ConfirmForgotPasswordText {
            get {
                return ResourceManager.GetString("ConfirmForgotPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete the image?.
        /// </summary>
        public static string DeleteImageQuestion {
            get {
                return ResourceManager.GetString("DeleteImageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exists..
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user already exists , hire your products from the admin panel.
        /// </summary>
        public static string EmailExistsCompany {
            get {
                return ResourceManager.GetString("EmailExistsCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to system@pay-in.es.
        /// </summary>
        public static string EmailUser {
            get {
                return ResourceManager.GetString("EmailUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Password..
        /// </summary>
        public static string ErrorPassword {
            get {
                return ResourceManager.GetString("ErrorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Estimado/a {2},&lt;/p&gt;
        ///&lt;p&gt;Para recuperar la contraseña haga click aquí: &lt;a href=&quot;{5}/Account/ConfirmForgotPassword?userid={0}&amp;code={1}&amp;email={3}&quot;&gt;{5}/Account/ConfirmForgotPassword&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;Si usted ha recibido este mensaje por error o no solicitó recuperar su contraseña, ignore y elimine este correo desde su bandeja de entrada.&lt;/p&gt;
        ///&lt;p&gt;¡Muchas gracias!&lt;/p&gt;.
        /// </summary>
        public static string ForgotPasswordContent {
            get {
                return ResourceManager.GetString("ForgotPasswordContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear {2},&lt;/ p&gt;&lt;p&gt;To confirm the password changed in APP Finestrat click here: &lt;a href=&quot;http://finestrat.pay-in.es/Account/ConfirmForgotPasswordFinestrat?userid={0}&amp;code={1}&amp;email={3}&quot;&gt;http://finestrat.pay-in.es/Account/ConfirmForgotPasswordFinestrat&lt;/a&gt;&lt;/p&gt; &lt;br /&gt; &lt;p&gt; If you wish to change your password, paste the user ID and the code in the corresponding boxes: &lt;p&gt; &lt;br /&gt; &lt;p&gt; User ID: &lt;strong&gt; {0} &lt;/ strong&gt; &lt;/ p&gt; &lt;br /&gt; &lt;p&gt; Code: &lt;strong&gt; {1} &lt;/ strong&gt; &lt;/ p&gt; &lt;br /&gt; &lt;p&gt; If you have received this messag [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ForgotPasswordContent_Finestrat {
            get {
                return ResourceManager.GetString("ForgotPasswordContent_Finestrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear {2},&lt;/ p&gt;&lt;p&gt;To confirm the password changed in APP Turisme Vilamarxant click here: &lt;a href=&quot;http://vilamarxant.pay-in.es/Account/ConfirmForgotPasswordTurismeVilamarxant?userid={0}&amp;code={1}&amp;email={3}&quot;&gt;http://vilamarxant.pay-in.es/Account/ConfirmForgotPasswordTurismeVilamarxant&lt;/a&gt;&lt;/p&gt; &lt;br /&gt; &lt;p&gt; If you wish to change your password, paste the user ID and the code in the corresponding boxes: &lt;p&gt; &lt;br /&gt; &lt;p&gt; User ID: &lt;strong&gt; {0} &lt;/ strong&gt; &lt;/ p&gt; &lt;br /&gt; &lt;p&gt; Code: &lt;strong&gt; {1} &lt;/ strong&gt; &lt;/ p&gt; &lt;br /&gt; &lt;p&gt;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ForgotPasswordContent_Vilamarxant {
            get {
                return ResourceManager.GetString("ForgotPasswordContent_Vilamarxant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar cambio de contraseña.
        /// </summary>
        public static string ForgotPasswordSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your {{arguments.email}} account password.
        /// </summary>
        public static string ForgotPasswordText {
            get {
                return ResourceManager.GetString("ForgotPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purse/foto{0}.jpeg.
        /// </summary>
        public static string FotoPurseShortUrl {
            get {
                return ResourceManager.GetString("FotoPurseShortUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purse/foto{0}.jpeg.
        /// </summary>
        public static string FotoPurseShortUrlTest {
            get {
                return ResourceManager.GetString("FotoPurseShortUrlTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://payin.blob.core.windows.net/files/purse/foto{0}.jpeg.
        /// </summary>
        public static string FotoPurseUrl {
            get {
                return ResourceManager.GetString("FotoPurseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://payintest.blob.core.windows.net/files/purse/foto{0}.jpeg.
        /// </summary>
        public static string FotoPurseUrlTest {
            get {
                return ResourceManager.GetString("FotoPurseUrlTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account/foto{0}.jpeg.
        /// </summary>
        public static string FotoShortUrl {
            get {
                return ResourceManager.GetString("FotoShortUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account/foto{0}.jpeg.
        /// </summary>
        public static string FotoShortUrlTest {
            get {
                return ResourceManager.GetString("FotoShortUrlTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://payin.blob.core.windows.net/files/account/foto{0}.jpeg.
        /// </summary>
        public static string FotoUrl {
            get {
                return ResourceManager.GetString("FotoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://payintest.blob.core.windows.net/files/account/foto{0}.jpeg.
        /// </summary>
        public static string FotoUrlTest {
            get {
                return ResourceManager.GetString("FotoUrlTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string HaveAccountQuestion {
            get {
                return ResourceManager.GetString("HaveAccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Pay-[In] account has been blocked for security reasons.
        /// </summary>
        public static string HeadMessageError {
            get {
                return ResourceManager.GetString("HeadMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your e- mail to confirm the registration , mail may be in the spam folder..
        /// </summary>
        public static string InfoEmail {
            get {
                return ResourceManager.GetString("InfoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Estimado/a  sr/sra,&lt;/p&gt;
        ///&lt;p&gt;Su empresa ha sido invitada como miembro de us Sistema de Tarjetas de la Plataforma Pay[in]. Por esta razón le hemos enviado este correo electrónico con el enlace que le permitirá completar el formulario de registro:&lt;/p&gt;
        ///&lt;a href=&quot;{4}/Account/ConfirmInvitedCompany?userid={0}&amp;code={1}&amp;email={3}&amp;name={2}&quot;&gt;{4}/Account/ConfirmInvitedCompany&lt;/a&gt;                   &lt;br /&gt;
        ///&lt;p&gt;Si ha recibido este correo por error, por favor ignore y elimine esta notificación de su bandeja de entrada.&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InviteCompanyUserEmailContent {
            get {
                return ResourceManager.GetString("InviteCompanyUserEmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Estimado/a  {2},&lt;/p&gt;
        ///&lt;p&gt;Ha sido invitado como usuario de la Plataforma {7}. Por esta razón le hemos enviado este correo electrónico con el enlace que le permitirá completar el formulario de registro:&lt;/p&gt;
        ///&lt;a href=&quot;{5}/Account/ConfirmInvitedUser?userid={0}&amp;code={1}&amp;email={3}&amp;name={2}&amp;phone={4}&amp;concessionPhotoUrl={6}&amp;concessionName={7}&quot;&gt;{5}/Account/ConfirmInvitedUser&lt;/a&gt;&lt;br /&gt;
        ///&lt;p&gt;Si ha recibido este correo por error, por favor ignore y elimine esta notificación de su bandeja de entrada.&lt;/p&gt;  
        ///&lt;p&gt;¡Muchas [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InviteUserEmailContent {
            get {
                return ResourceManager.GetString("InviteUserEmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma el registro en {0}.
        /// </summary>
        public static string InviteUserEmailSubject {
            get {
                return ResourceManager.GetString("InviteUserEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to get into the platform.
        /// </summary>
        public static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not have an account?.
        /// </summary>
        public static string NotHaveAccountQuestion {
            get {
                return ResourceManager.GetString("NotHaveAccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver a la Aplicación.
        /// </summary>
        public static string OpenSessionApp {
            get {
                return ResourceManager.GetString("OpenSessionApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesion Web.
        /// </summary>
        public static string OpenSessionWeb {
            get {
                return ResourceManager.GetString("OpenSessionWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Override {
            get {
                return ResourceManager.GetString("Override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear  Mr/Ms {0},&lt;/ p&gt;&lt;p&gt;Your  Pay-[In] password have been modified&lt;/p&gt; &lt;br /&gt; &lt;p&gt;If you have any question, do not hesitate to contact us at info@pay-in.es&lt;/p&gt; &lt;br /&gt; &lt;p&gt;If you have received this email in error, please ignore and delete it. &lt;/ p&gt;
        ///&lt;p&gt;Yours sincerely &lt;/ p&gt;.
        /// </summary>
        public static string OverridePasswordContent {
            get {
                return ResourceManager.GetString("OverridePasswordContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Password Notification.
        /// </summary>
        public static string OverridePasswordSubject {
            get {
                return ResourceManager.GetString("OverridePasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post a new password.
        /// </summary>
        public static string OverrideText {
            get {
                return ResourceManager.GetString("OverrideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least 6 characters long..
        /// </summary>
        public static string passwordLengthException {
            get {
                return ResourceManager.GetString("passwordLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (min. 6 characters).
        /// </summary>
        public static string PasswordMin {
            get {
                return ResourceManager.GetString("PasswordMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PIN must be 4 digits long..
        /// </summary>
        public static string PinLengthException {
            get {
                return ResourceManager.GetString("PinLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        public static string Recover {
            get {
                return ResourceManager.GetString("Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create user.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create company.
        /// </summary>
        public static string RegisterSupplier {
            get {
                return ResourceManager.GetString("RegisterSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register to get into the platform. .
        /// </summary>
        public static string RegisterText {
            get {
                return ResourceManager.GetString("RegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are a business, sign up as a company.
        /// </summary>
        public static string RegisterTextCompany {
            get {
                return ResourceManager.GetString("RegisterTextCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are a user, sign up as a user.
        /// </summary>
        public static string RegisterTextUser {
            get {
                return ResourceManager.GetString("RegisterTextUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I remember the password.
        /// </summary>
        public static string RememberPassword {
            get {
                return ResourceManager.GetString("RememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; Thank you! &lt;/ p&gt;.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        public static string SupplierName {
            get {
                return ResourceManager.GetString("SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax address.
        /// </summary>
        public static string TaxAddress {
            get {
                return ResourceManager.GetString("TaxAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax name.
        /// </summary>
        public static string TaxName {
            get {
                return ResourceManager.GetString("TaxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax number.
        /// </summary>
        public static string TaxNumber {
            get {
                return ResourceManager.GetString("TaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.pay-in.es/condiciones-de-servicio/.
        /// </summary>
        public static string TermsLink {
            get {
                return ResourceManager.GetString("TermsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for signing in the Pay[in] system.
        /// </summary>
        public static string ToastConfirmEmail {
            get {
                return ResourceManager.GetString("ToastConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for signing in the Pay[in] system. You will shortly receive an email in your account where you must confirm your registration. To do this, click on the link received in the mail . Please, if you do not receive the mail folder checks spam or attempts to register again . If you do not receive the mail emailed to system@pay-in.es..
        /// </summary>
        public static string ToastRegister {
            get {
                return ResourceManager.GetString("ToastRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear  Mr/Ms {0},&lt;/ p&gt;&lt;p&gt;Your  Pay-[In] user has been unlock&lt;/p&gt; &lt;br /&gt; &lt;p&gt;If you have any question, do not hesitate to contact us at info@pay-in.es&lt;/p&gt; &lt;br /&gt; &lt;p&gt;If you have received this email in error, please ignore and delete it. &lt;/ p&gt;
        ///&lt;p&gt;Yours sincerely &lt;/ p&gt;.
        /// </summary>
        public static string UnlockUserContent {
            get {
                return ResourceManager.GetString("UnlockUserContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock user notification.
        /// </summary>
        public static string UnlockUserSubject {
            get {
                return ResourceManager.GetString("UnlockUserSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdatePwd {
            get {
                return ResourceManager.GetString("UpdatePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        public static string UpdatePwdText {
            get {
                return ResourceManager.GetString("UpdatePwdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha introducido el Pin tres veces de forma incorrecta. Por seguridad hemos bloqueado su cuenta. Por favor, para resolver la incidencia póngase en contacto con nuestro administrador en info@pay-in.es..
        /// </summary>
        public static string UserBlocked {
            get {
                return ResourceManager.GetString("UserBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user Id.
        /// </summary>
        public static string userId {
            get {
                return ResourceManager.GetString("userId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check fields and make sure everything is fine..
        /// </summary>
        public static string ValidateConfirmForgotPassword {
            get {
                return ResourceManager.GetString("ValidateConfirmForgotPassword", resourceCulture);
            }
        }
    }
}
