//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayIn.Common.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayIn.Common.Resources.EnumResources", typeof(EnumResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cash.
        /// </summary>
        public static string AccountLineType_Cash {
            get {
                return ResourceManager.GetString("AccountLineType_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credit card.
        /// </summary>
        public static string AccountLineType_CreditCard {
            get {
                return ResourceManager.GetString("AccountLineType_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrances.
        /// </summary>
        public static string AccountLineType_Entrances {
            get {
                return ResourceManager.GetString("AccountLineType_Entrances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Others.
        /// </summary>
        public static string AccountLineType_Others {
            get {
                return ResourceManager.GetString("AccountLineType_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products.
        /// </summary>
        public static string AccountLineType_Products {
            get {
                return ResourceManager.GetString("AccountLineType_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Card.
        /// </summary>
        public static string AccountLineType_ServiceCard {
            get {
                return ResourceManager.GetString("AccountLineType_ServiceCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Day.
        /// </summary>
        public static string ApiSensorGetEnergyArguments_Period_Day {
            get {
                return ResourceManager.GetString("ApiSensorGetEnergyArguments_Period_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last 24h.
        /// </summary>
        public static string ApiSensorGetEnergyArguments_Period_Last24h {
            get {
                return ResourceManager.GetString("ApiSensorGetEnergyArguments_Period_Last24h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Day.
        /// </summary>
        public static string ApiSensorGetPowerArguments_Period_Day {
            get {
                return ResourceManager.GetString("ApiSensorGetPowerArguments_Period_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last 24h.
        /// </summary>
        public static string ApiSensorGetPowerArguments_Period_Last24h {
            get {
                return ResourceManager.GetString("ApiSensorGetPowerArguments_Period_Last24h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direct discount.
        /// </summary>
        public static string CampaignLineType_DirectDiscount {
            get {
                return ResourceManager.GetString("CampaignLineType_DirectDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Money.
        /// </summary>
        public static string CampaignLineType_Money {
            get {
                return ResourceManager.GetString("CampaignLineType_Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Percent.
        /// </summary>
        public static string CampaignLineType_Percent {
            get {
                return ResourceManager.GetString("CampaignLineType_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a P[check] – Control entrance/exit.
        /// </summary>
        public static string CheckPointType_Check {
            get {
                return ResourceManager.GetString("CheckPointType_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a P[in] – Control entrance.
        /// </summary>
        public static string CheckPointType_Entrance {
            get {
                return ResourceManager.GetString("CheckPointType_Entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a P[out] – Control exit.
        /// </summary>
        public static string CheckPointType_Exit {
            get {
                return ResourceManager.GetString("CheckPointType_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a P[round] – Control round.
        /// </summary>
        public static string CheckPointType_Round {
            get {
                return ResourceManager.GetString("CheckPointType_Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incident Check.
        /// </summary>
        public static string CheckType_Incident {
            get {
                return ResourceManager.GetString("CheckType_Incident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manual Check.
        /// </summary>
        public static string CheckType_Manual {
            get {
                return ResourceManager.GetString("CheckType_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NFC Check.
        /// </summary>
        public static string CheckType_NFC {
            get {
                return ResourceManager.GetString("CheckType_NFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Undefined.
        /// </summary>
        public static string CheckType_Undefined {
            get {
                return ResourceManager.GetString("CheckType_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Active.
        /// </summary>
        public static string ConcessionState_Active {
            get {
                return ResourceManager.GetString("ConcessionState_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending.
        /// </summary>
        public static string ConcessionState_Pending {
            get {
                return ResourceManager.GetString("ConcessionState_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Removed.
        /// </summary>
        public static string ConcessionState_Removed {
            get {
                return ResourceManager.GetString("ConcessionState_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suspended.
        /// </summary>
        public static string ConcessionState_Suspended {
            get {
                return ResourceManager.GetString("ConcessionState_Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check (To fullfil by user).
        /// </summary>
        public static string ControlFormArgumentTarget_Check {
            get {
                return ResourceManager.GetString("ControlFormArgumentTarget_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creation (To fullfil by operator).
        /// </summary>
        public static string ControlFormArgumentTarget_Creation {
            get {
                return ResourceManager.GetString("ControlFormArgumentTarget_Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Undefined.
        /// </summary>
        public static string ControlFormArgumentTarget_Undefined {
            get {
                return ResourceManager.GetString("ControlFormArgumentTarget_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes &amp; No.
        /// </summary>
        public static string ControlFormArgumentType_Bool {
            get {
                return ResourceManager.GetString("ControlFormArgumentType_Bool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        public static string ControlFormArgumentType_Date {
            get {
                return ResourceManager.GetString("ControlFormArgumentType_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date &amp; time.
        /// </summary>
        public static string ControlFormArgumentType_Datetime {
            get {
                return ResourceManager.GetString("ControlFormArgumentType_Datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decimal number.
        /// </summary>
        public static string ControlFormArgumentType_Double {
            get {
                return ResourceManager.GetString("ControlFormArgumentType_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duration.
        /// </summary>
        public static string ControlFormArgumentType_Duration {
            get {
                return ResourceManager.GetString("ControlFormArgumentType_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File.
        /// </summary>
        public static string ControlFormArgumentType_File {
            get {
                return ResourceManager.GetString("ControlFormArgumentType_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image.
        /// </summary>
        public static string ControlFormArgumentType_Image {
            get {
                return ResourceManager.GetString("ControlFormArgumentType_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Integer number.
        /// </summary>
        public static string ControlFormArgumentType_Int {
            get {
                return ResourceManager.GetString("ControlFormArgumentType_Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text.
        /// </summary>
        public static string ControlFormArgumentType_String {
            get {
                return ResourceManager.GetString("ControlFormArgumentType_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time.
        /// </summary>
        public static string ControlFormArgumentType_Time {
            get {
                return ResourceManager.GetString("ControlFormArgumentType_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ,.
        /// </summary>
        public static string DecimalCharDelimiter_Comma {
            get {
                return ResourceManager.GetString("DecimalCharDelimiter_Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ..
        /// </summary>
        public static string DecimalCharDelimiter_Dot {
            get {
                return ResourceManager.GetString("DecimalCharDelimiter_Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cleaning.
        /// </summary>
        public static string IncidenceCategory_Cleaning {
            get {
                return ResourceManager.GetString("IncidenceCategory_Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excrements.
        /// </summary>
        public static string IncidenceCategory_Excrements {
            get {
                return ResourceManager.GetString("IncidenceCategory_Excrements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Green Line.
        /// </summary>
        public static string IncidenceCategory_Green_Line {
            get {
                return ResourceManager.GetString("IncidenceCategory_Green_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lighting.
        /// </summary>
        public static string IncidenceCategory_Lighting {
            get {
                return ResourceManager.GetString("IncidenceCategory_Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Others.
        /// </summary>
        public static string IncidenceCategory_Others {
            get {
                return ResourceManager.GetString("IncidenceCategory_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parks and gardens.
        /// </summary>
        public static string IncidenceCategory_Parks_and_gardens {
            get {
                return ResourceManager.GetString("IncidenceCategory_Parks_and_gardens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Street furniture.
        /// </summary>
        public static string IncidenceCategory_Street_furniture {
            get {
                return ResourceManager.GetString("IncidenceCategory_Street_furniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Streets.
        /// </summary>
        public static string IncidenceCategory_Streets {
            get {
                return ResourceManager.GetString("IncidenceCategory_Streets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Active.
        /// </summary>
        public static string IncidenceState_Active {
            get {
                return ResourceManager.GetString("IncidenceState_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Closed.
        /// </summary>
        public static string IncidenceState_Closed {
            get {
                return ResourceManager.GetString("IncidenceState_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deleted.
        /// </summary>
        public static string IncidenceState_Deleted {
            get {
                return ResourceManager.GetString("IncidenceState_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Broken.
        /// </summary>
        public static string IncidenceSubCategory_Broken {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Broken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Broken branches.
        /// </summary>
        public static string IncidenceSubCategory_Broken_branches {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Broken_branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Broken lamp.
        /// </summary>
        public static string IncidenceSubCategory_Broken_lamp {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Broken_lamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cast lamp.
        /// </summary>
        public static string IncidenceSubCategory_Cast_lamp {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Cast_lamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Childish games.
        /// </summary>
        public static string IncidenceSubCategory_Childish_games {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Childish_games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cleaning of solar.
        /// </summary>
        public static string IncidenceSubCategory_Cleaning_of_solar {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Cleaning_of_solar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cleaning (several).
        /// </summary>
        public static string IncidenceSubCategory_Cleaning_varies {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Cleaning_varies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debris.
        /// </summary>
        public static string IncidenceSubCategory_Debris {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Debris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirty.
        /// </summary>
        public static string IncidenceSubCategory_Dirty {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Dirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dumpster.
        /// </summary>
        public static string IncidenceSubCategory_Dumpster {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Dumpster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipment.
        /// </summary>
        public static string IncidenceSubCategory_Equipment {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graffiti.
        /// </summary>
        public static string IncidenceSubCategory_Graffiti {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Graffiti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other (Green Line).
        /// </summary>
        public static string IncidenceSubCategory_Green_Line_Other {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Green_Line_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing.
        /// </summary>
        public static string IncidenceSubCategory_Missing {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other.
        /// </summary>
        public static string IncidenceSubCategory_Other {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Others.
        /// </summary>
        public static string IncidenceSubCategory_Others {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parkland.
        /// </summary>
        public static string IncidenceSubCategory_Parkland {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Parkland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pavement in poor condition.
        /// </summary>
        public static string IncidenceSubCategory_Pavement_in_poor_condition {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Pavement_in_poor_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plots.
        /// </summary>
        public static string IncidenceSubCategory_Plots {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Plots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pruning container.
        /// </summary>
        public static string IncidenceSubCategory_Pruning_container {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Pruning_container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Public road.
        /// </summary>
        public static string IncidenceSubCategory_Public_road {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Public_road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Risk of fire.
        /// </summary>
        public static string IncidenceSubCategory_Risk_of_fire {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Risk_of_fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sewerage.
        /// </summary>
        public static string IncidenceSubCategory_Sewerage {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Sewerage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Signaling.
        /// </summary>
        public static string IncidenceSubCategory_Signaling {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Signaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uncontrolled landfills.
        /// </summary>
        public static string IncidenceSubCategory_Uncontrolled_landfills {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Uncontrolled_landfills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Undergrowth.
        /// </summary>
        public static string IncidenceSubCategory_Undergrowth {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Undergrowth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Water leaks.
        /// </summary>
        public static string IncidenceSubCategory_Water_leaks {
            get {
                return ResourceManager.GetString("IncidenceSubCategory_Water_leaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ask.
        /// </summary>
        public static string IncidenceType_Ask {
            get {
                return ResourceManager.GetString("IncidenceType_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incidence.
        /// </summary>
        public static string IncidenceType_Incidence {
            get {
                return ResourceManager.GetString("IncidenceType_Incidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Others.
        /// </summary>
        public static string IncidenceType_Others {
            get {
                return ResourceManager.GetString("IncidenceType_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suggerence.
        /// </summary>
        public static string IncidenceType_Suggerence {
            get {
                return ResourceManager.GetString("IncidenceType_Suggerence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manual check.
        /// </summary>
        public static string IncidentType_ManualCheck {
            get {
                return ResourceManager.GetString("IncidentType_ManualCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other.
        /// </summary>
        public static string IncidentType_Other {
            get {
                return ResourceManager.GetString("IncidentType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presence.
        /// </summary>
        public static string IncidentType_Presence {
            get {
                return ResourceManager.GetString("IncidentType_Presence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept assignment.
        /// </summary>
        public static string NotificationType_AcceptAssignment {
            get {
                return ResourceManager.GetString("NotificationType_AcceptAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a American Express.
        /// </summary>
        public static string PaymentMediaType_AmericanExpress {
            get {
                return ResourceManager.GetString("PaymentMediaType_AmericanExpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MasterCard.
        /// </summary>
        public static string PaymentMediaType_MasterCard {
            get {
                return ResourceManager.GetString("PaymentMediaType_MasterCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visa.
        /// </summary>
        public static string PaymentMediaType_Visa {
            get {
                return ResourceManager.GetString("PaymentMediaType_Visa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Day.
        /// </summary>
        public static string PeriodType_Day {
            get {
                return ResourceManager.GetString("PeriodType_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last 24h.
        /// </summary>
        public static string PeriodType_Last24h {
            get {
                return ResourceManager.GetString("PeriodType_Last24h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control presence.
        /// </summary>
        public static string PinType_ControlPresence {
            get {
                return ResourceManager.GetString("PinType_ControlPresence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parking meter.
        /// </summary>
        public static string PinType_ParkingMeter {
            get {
                return ResourceManager.GetString("PinType_ParkingMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment media.
        /// </summary>
        public static string PinType_PaymentMedia {
            get {
                return ResourceManager.GetString("PinType_PaymentMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a P[in].
        /// </summary>
        public static string PresenceType_Entrance {
            get {
                return ResourceManager.GetString("PresenceType_Entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a P[out].
        /// </summary>
        public static string PresenceType_Exit {
            get {
                return ResourceManager.GetString("PresenceType_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Google.
        /// </summary>
        public static string ProviderMapType_Google {
            get {
                return ResourceManager.GetString("ProviderMapType_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nokia.
        /// </summary>
        public static string ProviderMapType_Nokia {
            get {
                return ResourceManager.GetString("ProviderMapType_Nokia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Even.
        /// </summary>
        public static string ServiceAddressSide_Even {
            get {
                return ResourceManager.GetString("ServiceAddressSide_Even", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Odd.
        /// </summary>
        public static string ServiceAddressSide_Odd {
            get {
                return ResourceManager.GetString("ServiceAddressSide_Odd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Card emitted.
        /// </summary>
        public static string ServiceOperationType_CardEmited {
            get {
                return ResourceManager.GetString("ServiceOperationType_CardEmited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Card Read.
        /// </summary>
        public static string ServiceOperationType_CardRead {
            get {
                return ResourceManager.GetString("ServiceOperationType_CardRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Card returned.
        /// </summary>
        public static string ServiceOperationType_CardReturned {
            get {
                return ResourceManager.GetString("ServiceOperationType_CardReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrance bought.
        /// </summary>
        public static string ServiceOperationType_EntranceBought {
            get {
                return ResourceManager.GetString("ServiceOperationType_EntranceBought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrance returned.
        /// </summary>
        public static string ServiceOperationType_EntranceReturned {
            get {
                return ResourceManager.GetString("ServiceOperationType_EntranceReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other.
        /// </summary>
        public static string ServiceOperationType_Other {
            get {
                return ResourceManager.GetString("ServiceOperationType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product bought.
        /// </summary>
        public static string ServiceOperationType_ProductBought {
            get {
                return ResourceManager.GetString("ServiceOperationType_ProductBought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product returned.
        /// </summary>
        public static string ServiceOperationType_ProductReturned {
            get {
                return ResourceManager.GetString("ServiceOperationType_ProductReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pruese recharged.
        /// </summary>
        public static string ServiceOperationType_PurseRecharged {
            get {
                return ResourceManager.GetString("ServiceOperationType_PurseRecharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Purse returned.
        /// </summary>
        public static string ServiceOperationType_PurseReturned {
            get {
                return ResourceManager.GetString("ServiceOperationType_PurseReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bought by TPV.
        /// </summary>
        public static string ServiceOperationType_TpvBought {
            get {
                return ResourceManager.GetString("ServiceOperationType_TpvBought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Returned by TPV.
        /// </summary>
        public static string ServiceOperationType_TpvReturned {
            get {
                return ResourceManager.GetString("ServiceOperationType_TpvReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Charge.
        /// </summary>
        public static string ServiceType_Charge {
            get {
                return ResourceManager.GetString("ServiceType_Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control.
        /// </summary>
        public static string ServiceType_Control {
            get {
                return ResourceManager.GetString("ServiceType_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ORA.
        /// </summary>
        public static string ServiceType_Ora {
            get {
                return ResourceManager.GetString("ServiceType_Ora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parking fine.
        /// </summary>
        public static string ServiceType_ParkingFine {
            get {
                return ResourceManager.GetString("ServiceType_ParkingFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Female.
        /// </summary>
        public static string SexType_Female {
            get {
                return ResourceManager.GetString("SexType_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Male.
        /// </summary>
        public static string SexType_Male {
            get {
                return ResourceManager.GetString("SexType_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Undefined.
        /// </summary>
        public static string SexType_Undefined {
            get {
                return ResourceManager.GetString("SexType_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buy.
        /// </summary>
        public static string TicketLineType_Buy {
            get {
                return ResourceManager.GetString("TicketLineType_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Discount.
        /// </summary>
        public static string TicketLineType_Discount {
            get {
                return ResourceManager.GetString("TicketLineType_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrances.
        /// </summary>
        public static string TicketLineType_Entrance {
            get {
                return ResourceManager.GetString("TicketLineType_Entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estra price.
        /// </summary>
        public static string TicketLineType_ExtraPrice {
            get {
                return ResourceManager.GetString("TicketLineType_ExtraPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products.
        /// </summary>
        public static string TicketLineType_Product {
            get {
                return ResourceManager.GetString("TicketLineType_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recharge.
        /// </summary>
        public static string TicketLineType_Recharge {
            get {
                return ResourceManager.GetString("TicketLineType_Recharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Return card.
        /// </summary>
        public static string TicketLineType_ReturnCard {
            get {
                return ResourceManager.GetString("TicketLineType_ReturnCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Active.
        /// </summary>
        public static string TicketStateType_Active {
            get {
                return ResourceManager.GetString("TicketStateType_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelled.
        /// </summary>
        public static string TicketStateType_Cancelled {
            get {
                return ResourceManager.GetString("TicketStateType_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ParciallyPayed.
        /// </summary>
        public static string TicketStateType_ParciallyPayed {
            get {
                return ResourceManager.GetString("TicketStateType_ParciallyPayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payed.
        /// </summary>
        public static string TicketStateType_Payed {
            get {
                return ResourceManager.GetString("TicketStateType_Payed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not payable.
        /// </summary>
        public static string TicketType_NotPayable {
            get {
                return ResourceManager.GetString("TicketType_NotPayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order.
        /// </summary>
        public static string TicketType_Order {
            get {
                return ResourceManager.GetString("TicketType_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recharge.
        /// </summary>
        public static string TicketType_Recharge {
            get {
                return ResourceManager.GetString("TicketType_Recharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shipment.
        /// </summary>
        public static string TicketType_Shipment {
            get {
                return ResourceManager.GetString("TicketType_Shipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ticket.
        /// </summary>
        public static string TicketType_Ticket {
            get {
                return ResourceManager.GetString("TicketType_Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Active.
        /// </summary>
        public static string WorkerState_Active {
            get {
                return ResourceManager.GetString("WorkerState_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deleted.
        /// </summary>
        public static string WorkerState_Deleted {
            get {
                return ResourceManager.GetString("WorkerState_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending.
        /// </summary>
        public static string WorkerState_Pending {
            get {
                return ResourceManager.GetString("WorkerState_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unsuscribed.
        /// </summary>
        public static string WorkerState_Unsuscribed {
            get {
                return ResourceManager.GetString("WorkerState_Unsuscribed", resourceCulture);
            }
        }
    }
}
