//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayIn.Common.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayIn.Common.Resources.HomeResources", typeof(HomeResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deals.
        /// </summary>
        public static string Deals {
            get {
                return ResourceManager.GetString("Deals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First month at 0,5%.
        /// </summary>
        public static string FirstMonth05 {
            get {
                return ResourceManager.GetString("FirstMonth05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First month free comission.
        /// </summary>
        public static string FirstMonthFree {
            get {
                return ResourceManager.GetString("FirstMonthFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose the plan that best suits your needs..
        /// </summary>
        public static string InfoDeals {
            get {
                return ResourceManager.GetString("InfoDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LAUNCH OFFER.
        /// </summary>
        public static string LaunchOffer {
            get {
                return ResourceManager.GetString("LaunchOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No maintenance.
        /// </summary>
        public static string NoMaintenance {
            get {
                return ResourceManager.GetString("NoMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No setup fee.
        /// </summary>
        public static string NoSetUpFee {
            get {
                return ResourceManager.GetString("NoSetUpFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prices excluding VAT.
        /// </summary>
        public static string NoVat {
            get {
                return ResourceManager.GetString("NoVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a / transaction.
        /// </summary>
        public static string PerTransaction {
            get {
                return ResourceManager.GetString("PerTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}.
        /// </summary>
        public static string PopupMessage {
            get {
                return ResourceManager.GetString("PopupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notification.
        /// </summary>
        public static string PopupTitle {
            get {
                return ResourceManager.GetString("PopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Purchase.
        /// </summary>
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Second month at 0,5%.
        /// </summary>
        public static string SecondMonth05 {
            get {
                return ResourceManager.GetString("SecondMonth05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monthly statistical report.
        /// </summary>
        public static string StatisticalReport {
            get {
                return ResourceManager.GetString("StatisticalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Third month and forward 1%.
        /// </summary>
        public static string ThirdMonth1 {
            get {
                return ResourceManager.GetString("ThirdMonth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create a new concession.
        /// </summary>
        public static string TittleOffers {
            get {
                return ResourceManager.GetString("TittleOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Upgrade to Supplier.
        /// </summary>
        public static string Upgrade {
            get {
                return ResourceManager.GetString("Upgrade", resourceCulture);
            }
        }
    }
}
