//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayIn.Common.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NoticeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NoticeResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayIn.Common.Resources.NoticeResources", typeof(NoticeResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://payin.blob.core.windows.net/files/notice/photo/Photo_{0}.jpg.
        /// </summary>
        public static string PhotoShortUrl {
            get {
                return ResourceManager.GetString("PhotoShortUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a notice/photo/Photo_{0}.jpg.
        /// </summary>
        public static string PhotoUrl {
            get {
                return ResourceManager.GetString("PhotoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://fallas.blob.core.windows.net/files/notice/photo/Photo_{0}.jpg.
        /// </summary>
        public static string PhotoUrlFallas {
            get {
                return ResourceManager.GetString("PhotoUrlFallas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://payintest.blob.core.windows.net/files/notice/photo/Photo_{0}.jpg.
        /// </summary>
        public static string PhotoUrlTest {
            get {
                return ResourceManager.GetString("PhotoUrlTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://vilamarxant.blob.core.windows.net/files/notice/photo/Photo_{0}.jpg.
        /// </summary>
        public static string PhotoUrlVilamarxant {
            get {
                return ResourceManager.GetString("PhotoUrlVilamarxant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a notice/route/Route_{0}.gpx.
        /// </summary>
        public static string RouteGPXFile {
            get {
                return ResourceManager.GetString("RouteGPXFile", resourceCulture);
            }
        }
    }
}
