//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayIn.Common.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PaymentConcessionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentConcessionResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayIn.Common.Resources.PaymentConcessionResources", typeof(PaymentConcessionResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Office Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IBAN Account Number.
        /// </summary>
        public static string BankAccountNumber {
            get {
                return ResourceManager.GetString("BankAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concession fields.
        /// </summary>
        public static string ConcessionForm {
            get {
                return ResourceManager.GetString("ConcessionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concession Name.
        /// </summary>
        public static string ConcessionName {
            get {
                return ResourceManager.GetString("ConcessionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your Supplier and Concession have been created right. We will activate them as soon as possible. Please, you should log out to apply changes..
        /// </summary>
        public static string ConfirmPaymentConcession {
            get {
                return ResourceManager.GetString("ConfirmPaymentConcession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create payment concession.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data Responsible.
        /// </summary>
        public static string DataResponsible {
            get {
                return ResourceManager.GetString("DataResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a paymentconcession/Concession_{0}_{1}.zip.
        /// </summary>
        public static string FileShortUrl {
            get {
                return ResourceManager.GetString("FileShortUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning: The maximum size of all files is 10MB.
        /// </summary>
        public static string fileSizeWarning {
            get {
                return ResourceManager.GetString("fileSizeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://payin.blob.core.windows.net/files/paymentconcession/Concession_{0}_{1}.zip.
        /// </summary>
        public static string FileUrl {
            get {
                return ResourceManager.GetString("FileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://payintest.blob.core.windows.net/files/paymentconcession/Concession_{0}_{1}.zip.
        /// </summary>
        public static string FileUrlTest {
            get {
                return ResourceManager.GetString("FileUrlTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Self-employed form or VAT.
        /// </summary>
        public static string FormA {
            get {
                return ResourceManager.GetString("FormA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Form File.
        /// </summary>
        public static string FormUrl {
            get {
                return ResourceManager.GetString("FormUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Income Tax.
        /// </summary>
        public static string IncomeTax {
            get {
                return ResourceManager.GetString("IncomeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Commercial information.
        /// </summary>
        public static string InformationComercial {
            get {
                return ResourceManager.GetString("InformationComercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tax information.
        /// </summary>
        public static string InformationTax {
            get {
                return ResourceManager.GetString("InformationTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To register a new supplier we need tax information and to ensure its authenticity..
        /// </summary>
        public static string InformationTaxDescription {
            get {
                return ResourceManager.GetString("InformationTaxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Liquidation Amount  Min.
        /// </summary>
        public static string LiquidationAmountMin {
            get {
                return ResourceManager.GetString("LiquidationAmountMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Liquidation Date.
        /// </summary>
        public static string LiquidationRequestDate {
            get {
                return ResourceManager.GetString("LiquidationRequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observations.
        /// </summary>
        public static string Observations {
            get {
                return ResourceManager.GetString("Observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pay-[In] Commission.
        /// </summary>
        public static string PayinCommission {
            get {
                return ResourceManager.GetString("PayinCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Concession.
        /// </summary>
        public static string PaymentConcession {
            get {
                return ResourceManager.GetString("PaymentConcession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concession not found.
        /// </summary>
        public static string PaymentConcessionNotFound {
            get {
                return ResourceManager.GetString("PaymentConcessionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Concessions List.
        /// </summary>
        public static string PaymentConcessionsList {
            get {
                return ResourceManager.GetString("PaymentConcessionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://payin.blob.core.windows.net/files/paymentConcession/photo/Photo_{0}.jpg.
        /// </summary>
        public static string PhotoShortUrl {
            get {
                return ResourceManager.GetString("PhotoShortUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a paymentConcession/photo/Photo_{0}.jpg.
        /// </summary>
        public static string PhotoUrl {
            get {
                return ResourceManager.GetString("PhotoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://payintest.blob.core.windows.net/files/paymentConcession/photo/Photo_{0}.jpg.
        /// </summary>
        public static string PhotoUrlTest {
            get {
                return ResourceManager.GetString("PhotoUrlTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pin.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pin Confirmation.
        /// </summary>
        public static string PinConfirmation {
            get {
                return ResourceManager.GetString("PinConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To pay or refund payments you need a PIN to authorize it. Must be 4 digits.
        /// </summary>
        public static string PinDescription {
            get {
                return ResourceManager.GetString("PinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pin accepts 4 digits only.
        /// </summary>
        public static string PinErrorMessage {
            get {
                return ResourceManager.GetString("PinErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To refund payments you must use the PIN entered when adding the first card.
        /// </summary>
        public static string PinNonDescription {
            get {
                return ResourceManager.GetString("PinNonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XX00 0000 0000 0000 0000 0000.
        /// </summary>
        public static string PlaceHolderAccount {
            get {
                return ResourceManager.GetString("PlaceHolderAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supplier Name.
        /// </summary>
        public static string SupplierName {
            get {
                return ResourceManager.GetString("SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tax Address.
        /// </summary>
        public static string TaxAddress {
            get {
                return ResourceManager.GetString("TaxAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tax Name.
        /// </summary>
        public static string TaxName {
            get {
                return ResourceManager.GetString("TaxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tax Number.
        /// </summary>
        public static string TaxNumber {
            get {
                return ResourceManager.GetString("TaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Payment Concession.
        /// </summary>
        public static string UpdatePaymentConcession {
            get {
                return ResourceManager.GetString("UpdatePaymentConcession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vat.
        /// </summary>
        public static string Vat {
            get {
                return ResourceManager.GetString("Vat", resourceCulture);
            }
        }
    }
}
