//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayIn.Common.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PaymentUserResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentUserResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayIn.Common.Resources.PaymentUserResources", typeof(PaymentUserResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were added as a client in {0}. Do you accept this association?.
        /// </summary>
        public static string AcceptAssociationMessage {
            get {
                return ResourceManager.GetString("AcceptAssociationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has accepted the association in {1} as a client.
        /// </summary>
        public static string AssociationAccepted {
            get {
                return ResourceManager.GetString("AssociationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has refused the association as a client in {1}.
        /// </summary>
        public static string AssociationRefused {
            get {
                return ResourceManager.GetString("AssociationRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not delete a payment user with one or more pending tickets ..
        /// </summary>
        public static string DeleteException {
            get {
                return ResourceManager.GetString("DeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your were removed from {0} payment workers list..
        /// </summary>
        public static string DissociationMessage {
            get {
                return ResourceManager.GetString("DissociationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not create yourself as a client.
        /// </summary>
        public static string EmailClientCommerce {
            get {
                return ResourceManager.GetString("EmailClientCommerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The introduced email is already used by another worker.
        /// </summary>
        public static string ExceptionUserMailAlreadyExists {
            get {
                return ResourceManager.GetString("ExceptionUserMailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay[in]: {0}.
        /// </summary>
        public static string Personalized {
            get {
                return ResourceManager.GetString("Personalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finestrat: {0}.
        /// </summary>
        public static string Personalized_Finestrat {
            get {
                return ResourceManager.GetString("Personalized_Finestrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vilamarxant: {0}.
        /// </summary>
        public static string Personalized_TurismeVilamarxant {
            get {
                return ResourceManager.GetString("Personalized_TurismeVilamarxant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not make a refund of this ticket, contact your commerce to perform this operation.
        /// </summary>
        public static string RefundNotAllowed {
            get {
                return ResourceManager.GetString("RefundNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have accepted the association as a client in {0}..
        /// </summary>
        public static string UserAssociationAccepted {
            get {
                return ResourceManager.GetString("UserAssociationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} removed himself from the {1} clients list..
        /// </summary>
        public static string UserDissociationMessage {
            get {
                return ResourceManager.GetString("UserDissociationMessage", resourceCulture);
            }
        }
    }
}
