//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayIn.Common.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PaymentConcessionCampaignResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentConcessionCampaignResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayIn.Common.Resources.PaymentConcessionCampaignResources", typeof(PaymentConcessionCampaignResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You were added as a company for campaigns in {0}. Do you accept this association?.
        /// </summary>
        public static string AcceptAssociationMessage {
            get {
                return ResourceManager.GetString("AcceptAssociationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You were added as a company for purses in {0}. Do you accept this association?.
        /// </summary>
        public static string AcceptAssociationMessagePurse {
            get {
                return ResourceManager.GetString("AcceptAssociationMessagePurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The company you&apos;re trying to add has already been added to this campaign.
        /// </summary>
        public static string AddException {
            get {
                return ResourceManager.GetString("AddException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This company already exists, assign a campaign..
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has accepted the association to the {1} campaign.
        /// </summary>
        public static string AssociationAccepted {
            get {
                return ResourceManager.GetString("AssociationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has refused the association to {1} campaign.
        /// </summary>
        public static string AssociationRefused {
            get {
                return ResourceManager.GetString("AssociationRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You were removed from {0} concession campaign list..
        /// </summary>
        public static string DissociationMessage {
            get {
                return ResourceManager.GetString("DissociationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No associated campaign..
        /// </summary>
        public static string NoCampaign {
            get {
                return ResourceManager.GetString("NoCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The company you&apos;re trying to add does not exist..
        /// </summary>
        public static string PaymentConcessionException {
            get {
                return ResourceManager.GetString("PaymentConcessionException", resourceCulture);
            }
        }
    }
}
