//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayIn.Common.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceWorkerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceWorkerResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayIn.Common.Resources.ServiceWorkerResources", typeof(ServiceWorkerResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept Assignment.
        /// </summary>
        public static string AcceptAssignment {
            get {
                return ResourceManager.GetString("AcceptAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://control.pay-in.es/ServiceWorker/AcceptAssignment.
        /// </summary>
        public static string AcceptAssignmentUrl {
            get {
                return ResourceManager.GetString("AcceptAssignmentUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;p&gt;Dear {0},&lt;/p&gt;
        ///&lt;p&gt;You were assigned to be a worker. For this reason, we have sent this mail with this link to Login and then confirm your assignment.&lt;/p&gt;
        ///&lt;a href=&quot;https://control.pay-in.es/Account/Login&quot;&gt; https://control.pay-in.es/Account/Login&lt;/a&gt;
        ///&lt;p&gt;Thank you very much&lt;/p&gt;.
        /// </summary>
        public static string AsignationMailContent {
            get {
                return ResourceManager.GetString("AsignationMailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept assignment as a worker.
        /// </summary>
        public static string AsignationMailSubject {
            get {
                return ResourceManager.GetString("AsignationMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has accepted the association as a service worker in {1}.
        /// </summary>
        public static string AssociationAccepted {
            get {
                return ResourceManager.GetString("AssociationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has refused the association as a service worker in {1}.
        /// </summary>
        public static string AssociationRefused {
            get {
                return ResourceManager.GetString("AssociationRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create worker.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete worker.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to delete the worker {0}?.
        /// </summary>
        public static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The introduced email is already used by another worker.
        /// </summary>
        public static string ExceptionWorkerMailAlreadyExists {
            get {
                return ResourceManager.GetString("ExceptionWorkerMailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The number of workers of your company can not exceed the maximum number of workers indicated.
        /// </summary>
        public static string ExceptionWorkerMaxWorkers {
            get {
                return ResourceManager.GetString("ExceptionWorkerMaxWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workers.
        /// </summary>
        public static string GetAll {
            get {
                return ResourceManager.GetString("GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has Accepted.
        /// </summary>
        public static string HasAccepted {
            get {
                return ResourceManager.GetString("HasAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workers.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update worker.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Worker.
        /// </summary>
        public static string Worker {
            get {
                return ResourceManager.GetString("Worker", resourceCulture);
            }
        }
    }
}
