//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayIn.Common.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceUserResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceUserResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PayIn.Common.Resources.ServiceUserResources", typeof(ServiceUserResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serviceuser/assertdoc/AssertDoc_{0}_{1}.zip.
        /// </summary>
        public static string AssertDocShortUrl {
            get {
                return ResourceManager.GetString("AssertDocShortUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://payin.blob.core.windows.net/files/serviceuser/assertdoc/AssertDoc_{0}_{1}.zip.
        /// </summary>
        public static string AssertDocUrl {
            get {
                return ResourceManager.GetString("AssertDocUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://payintest.blob.core.windows.net/files/serviceuser/assertdoc/AssertDoc_{0}_{1}.zip.
        /// </summary>
        public static string AssertDocUrlTest {
            get {
                return ResourceManager.GetString("AssertDocUrlTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serviceuser/photo/Photo_{0}.jpg.
        /// </summary>
        public static string PhotoShortUrl {
            get {
                return ResourceManager.GetString("PhotoShortUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://payin.blob.core.windows.net/files/serviceuser/photo/Photo_{0}.jpg.
        /// </summary>
        public static string PhotoUrl {
            get {
                return ResourceManager.GetString("PhotoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://payintest.blob.core.windows.net/files/serviceuser/photo/Photo_{0}.jpg.
        /// </summary>
        public static string PhotoUrlTest {
            get {
                return ResourceManager.GetString("PhotoUrlTest", resourceCulture);
            }
        }
    }
}
